apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web3-transaction-assembler.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web3-transaction-assembler.labels" . | nindent 8 }}
data:
  ETHEREUM_RPC_URL: {{ .Values.config.ethereumRpcUrl | quote }}
  POLYGON_RPC_URL: {{ .Values.config.polygonRpcUrl | quote }}
  BASE_RPC_URL: {{ .Values.config.baseRpcUrl | quote }}
  SOLANA_RPC_URL: {{ .Values.config.solanaRpcUrl | quote }}
  BITCOIN_BLOCKSTREAM_API: {{ .Values.config.bitcoinBlockstreamApi | quote }}
  API_PORT: {{ .Values.service.httpPort | quote }}